### PR TITLE
Add support for soap headers in AuthenticatedRequest

### PR DESCRIPTION
**Pull request by nitsky**
This provides a solution for Issue #16. I added a `headers` field to `Client`. Below is an example.

```
import beatbox
svc = beatbox.Client()
svc.login('test@test.com', 'test')
svc.headers = {
    'EmailHeader': {
        'triggerAutoResponseEmail': True,
    },
    'AssignmentRuleHeader': {
        'useDefaultRule': True,
    },
}
svc.create({
  'type': 'Case',
  ... 
})
```

### CODE REVIEW

**Comment by superfell** [comment]
Thanks, i'll look at merging this after finalizing #31

**Comment by hynekcer** [comment]
It looks good. I have a more general solution, but I'm also waiting with it for #31.

**Comment by hynekcer** [comment]
It is good that no public methods are modified. I will not add or generalize anything related to this PR until you suppose that everything is ready.
- It is easier if PR #37 will be pulled before this. It can be easily verified that it is equivalent code, but it would not be easy to merge #34 to the current master without #37.
- I fixed an issue with SOAP headers and Python 3. Headers are usually small and it is better to use `items` instead of `iteritems` than to call a complicated `operator.methodcaller("items")` on every dictionary if you would insist on iterator also in Python 2.
- It is interesting, that tests from unittest branch passed with the invalid code. The method AuthenticatedRequest.writeHeaders should be covered by a test.
- Some short documentation would be useful.

**Comment by superfell** [comment]
Thanks!

**Pull request merged**
